### ISSUE TITLE
Add CODEOWNERS + Turn on branch protection

### ISSUE THREAD

**Issue by OR13** [w3c/did-wg#30]
Block any merges when changes are requested.

Dismiss stale reviews (request re-reviews)...

make it clear when things are ready to merge, and when things are blocked... and by who they are blocked (so you can ask for feedback).

**Comment by brentzundel** [comment]
Moved to did-wg as it potentially applies to all DID WG repositories.

**Comment by burnburn** [comment]
Ivan was not completely clear on what he needed to do here.  Can you comment, @iherman ?

**Comment by OR13** [comment]
IMO:

need to create a file "CODEOWNERS" in each repo, for example: https://github.com/w3c-ccg/vc-issuer-http-api/blob/master/CODEOWNERS

need to turn on branch protection for master, and require approval from at least 1 code owner.

**Comment by iherman** [comment]
@OR13 I must admit I was not familiar with this feature. 

As an info: there _is_ already a branch protection set for all repositories: only the editors have the possibility to merge into the main branch (which also triggers an automatic publication of the document). My understanding is that this code owner feature will set a review request on all editors for all PR-s. I believe that this is something that the editorial teams of each repository should decide: if they agree to use this, I have no reason not to agree...

@peacekeeper @jandrieu @philarcher @msporny @talltree

**Comment by iherman** [comment]
grossly outdated. Closing
