### ISSUE TITLE
rename master branches

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-wg#34]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [x]  create main branch from master
- [ ]  make main the default GitHub branch
- [ ]  modify github/central to use main for release notes reloading
- [ ]  redirect PRs to main in all did wg repos
- [ ]  move branch protections from master to main
- [ ]  modify docs to reference main instead of master
- [ ]  delete master branch to avoid confusion?

Feedback?

**Comment by iherman** [comment]
https://github.com/w3c/did-core/issues/332#issuecomment-648238546

**Comment by iherman** [comment]
B.t.w., if we get to the point when this can be done, we should also cross-check whether jekyll works properly and what changes should be done.

**Comment by iherman** [comment]
This is a joint comment for all the repositories with a similar issue, namely https://github.com/w3c/did-core/issues/332, https://github.com/w3c/did-spec-registries/issues/76, https://github.com/w3c/did-use-cases/issues/88, https://github.com/w3c/did-rubric/issues/3, and https://github.com/w3c/did-imp-guide/issues/1 :

Github has changed its user interface and operation, and it is now possible to set _any_ branch as the target for github.io. In other words, it _is_ possible to take the renaming actions.

I must admit I am a bit worried about whether there will be complications doing that, though. For example, I do not know whether this would require the manual reconfiguration of various clients (git plugins to various editors, GitRaken, Sourcetree, etc) people may use, what would happen to all the current open PR-s, etc. Anybody has experience with this, before we engage into this (if at all)?

**Comment by brentzundel** [comment]
It looks like they're still working on tooling to make this easier: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by brentzundel** [comment]
@iherman @burnburn  would you be opposed to an experiment with this repo? 
I have created a main branch. 
I would like to set it as the default branch.

There are currently no PRs and the issues shouldn't be affected at all.

What will break when we do this? I know our DID WG website pulls information from this repository (I assume from the master branch), so I imagine that link will need to change. I am sure there are other things that will be broken. 

I would like to try it and see, but will certainly wait if either of you would rather I don't do it just yet.

**Comment by davidlehn** [comment]
@brentzundel Run "experiments" on a test repo first, not an active live one.

**Comment by iherman** [comment]
I am always worried of such things, to be honest. As an example that comes to my mind: I am not fully familiar with how the 'built-in' jekyll works, I am just a user at best. Are we sure that jekyll is adapted to such a change, ie, it can survive the change of the default branch to generate the home page? 

I would agree with @davidlehn on this.

**Comment by brentzundel** [comment]
> @brentzundel Run "experiments" on a test repo first, not an active live one.

Can you point me to a test repo that might actually give us the feedback we need?

**Comment by davidlehn** [comment]
> > @brentzundel Run "experiments" on a test repo first, not an active live one.
> 
> Can you point me to a test repo that might actually give us the feedback we need?

Probably easiest to create one or more new repos in your own namespace, set them up similar to w3c ones, try out changes, and make sure changes work.

**Comment by brentzundel** [comment]
> > > @brentzundel Run "experiments" on a test repo first, not an active live one.
> > 
> > 
> > Can you point me to a test repo that might actually give us the feedback we need?
> 
> Probably easiest to create one or more new repos in your own namespace, set them up similar to w3c ones, try out changes, and make sure changes work.

Could someone point me to a tutorial on how to set up a repo similar to a W3C one?

Or maybe I could flip the switch on this one, and if too much stuff falls apart, just flip the switch back?

**Comment by iherman** [comment]
I a bit afraid this repo may not be very representative: it doesn't have respec documents, and, on the other hand, is using Jekyll, whis is very special.

I guess if you set up a repo with some html documents, where you make a bunch of pull requests (before swithing the default and 'paged' master branch), merge them, and then change the default including the paging. The question is whether the history, former links, etc, will survive.

I am sure there are other things to check. For example ECHIDNA...

**Comment by iherman** [comment]
All done on the 2021-03-25.
