### ISSUE TITLE
How to register did method

### ISSUE THREAD

**Issue by niyuelin1990** [w3c/did-wg#43]
How does our company register a did method，Such as did:transfer,  and what materials need to be provided。
Then it can be displayed on the web page (https://w3c.github.io/did-spec-registries/#did-methods)

**Comment by talltree** [comment]
First you need to write a DID method specification. See the current [DID Core Specification](https://w3c.github.io/did-core/) for requirements. Once you have that posted someplace on the Web where we can review it, you can submit a request to have it added to the [DID Spec Registries](https://www.w3.org/TR/did-spec-registries/).

**Comment by iherman** [comment]
grossly outdated. Closing
