### ISSUE TITLE
Formal objections need a separate response

### ISSUE THREAD

**Issue by rxgrant** [w3c/did-wg#50]
In [did-imp-guide pull/27](/w3c/did-imp-guide/pull/27) there is an attempt to address the formal objections with wording that cannot in detail meet the concerns of the objectors, and that - in its current vague disapproval of proof-of-work DID methods as shown by calling them out under special requirements - cannot gain consensus.

It is possible to meet some possible concerns of the formal objectors if more precisely answering the implicit accusation with details about a specific DID method.  

As one of the authors of a DID method relying on proof-of-work, I'm volunteering to lead writing a response that other WG members *may* sign on to if they agree.  This could end up as a WG Note, but if it's voted down then it will end up as a mailing list email.  

In particular, I believe that along with practical reasoning, a [causal model](https://plato.stanford.edu/entries/causal-models/#fig3) connecting the anchoring of DIDs on the Bitcoin blockchain to the alleged "fail" of the [TAG/EWP sustainability goal](https://www.w3.org/2001/tag/doc/ethical-web-principles/#sustainable) will help all parties speak more intelligently about the issue.  

Using this form of reasoning it is possible to examine the addition of each DID method anchoring transaction to the Bitcoin blockchain and quantify the additional motive to burn carbon-based fuels for electricity.  This metric can be used to offset the carbon polluted into the atmosphere.

Two DID methods that will be discussed are did:btcr and did:ion.  I will also critique conflicting TAG/EWP goals, discuss other moral concerns, point to transistions underway in the energy sector and speak about the economic incentives to use renewable energy, offer an example criteria to add to the Rubric so that end users can make later use of the reasoning, and offer to act as editor coordinating sections on other aspects of the formal objections, such as the request for a mandatory reference method.

Based on feedback so far, most people think that references to TAG/EWP in the Implementation Guide is enough.  If that's the only response, then the concerns of the formal objectors will not be addressed directly.

**Comment by rxgrant** [comment]
The DID WG met and seemed to have consensus around redirecting discussion to the Rubric.  I'll start with that.

**Comment by iherman** [comment]
Outdated and processed. Closing
